export const primaryDark=`#27292B`,
primaryGrey=`#535456`,
primaryCrema=`#E9E0D2`,
primaryLight=`#F9F5F0`,
secondaryDark=`#45484B`,
secondaryGrey=`#828282`,
secondaryCrema=`#F4EFE6`,
secondaryLight=`#FFFFFF`,
errorDark= `#B02525`,
errorLight= `#EBA7A7`,
successDark= `#179843`,
successLight=`#95DCAD`,
alertDark=`#C6811A`,
alertLight=`#E5CBA4`,
infoDark=`#174B98`,
infoLight=`#7E9FD0`;

export default {
  light: {
    text: primaryDark,
    background: primaryLight,
    tint: primaryLight,
    tabSelected: `#D5C5AD`,
    tabIconDefault: primaryGrey,
    tabIconSelected: primaryDark,
    tabBackground: primaryCrema,
    labelColor: secondaryGrey,
    postBackground: secondaryLight,
    header: secondaryCrema,
    headerText: primaryGrey,
  },
  dark: {
    text: primaryLight,
    background: secondaryDark,
    tint: secondaryGrey,
    tabIconDefault: secondaryCrema,
    tabIconSelected: primaryCrema,
    labelColor: primaryCrema,
    postBackground: secondaryGrey,
    tabSelected: primaryGrey,
    tabBackground: secondaryGrey,
    header: secondaryGrey,
    headerText: primaryLight,
  },
};
