export const primaryDark=`#27292B`,
primaryGrey=`#535456`,
primaryCrema=`#E9E0D2`,
primaryLight=`#F9F5F0`,
secondaryDark=`#45484B`,
secondaryGrey=`#828282`,
secondaryCrema=`#F4EFE6`,
secondaryLight=`#FFFFFF`,
errorDark= `#B02525`,
errorLight= `#D07575`,
successDark= `#179843`,
successLight=`#83D39F`,
alertDark=`#C6811A`,
alertLight=`#CFAC78`,
infoDark=`#174B98`,
infoLight=`#7E9FD0`;

export default {
  light: {
    text: primaryDark,
    background: primaryLight,
    tint: primaryLight,
    tabSelected: `#D5C5AD`,
    tabIconDefault: primaryGrey,
    tabBackground: primaryCrema,
    labelColor: secondaryGrey,
    postBackground: secondaryLight,
  },
  dark: {
    text: primaryLight,
    background: secondaryDark,
    tint: secondaryGrey,
    tabIconDefault: '#ccc',
    tabIconSelected: secondaryGrey,
    labelColor: primaryCrema,
    postBackground: secondaryGrey,
    tabSelected: primaryCrema,
    tabBackground: primaryCrema,
  },
};
